name: ci

on:
#  workflow_dispatch:
  push:
    branches:
      - 'main'

jobs:
  angular:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false
      - name: Node 18
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: NPM Install
        run: npm install --prefix client
      - name: NG Build
        run: npm run build --prefix client
        
  docker:
    runs-on: ubuntu-latest
    needs: angular
    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: "{{defaultContext}}:API"
          push: true
          tags: loganphx/datingapp:latest
